import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

// Shared secret key for HMAC signature verification
const SECRET_KEY = process.env.ZENITH_SECRET_KEY || 'zenith_study_site_secure_token_2026';

// Allowed origins
const ALLOWED_ORIGINS = [
  'https://zenithstudy.site',
  'https://www.zenithstudy.site',
  'http://localhost:3000',
  'http://localhost:5173',
  'http://127.0.0.1:3000',
  'http://127.0.0.1:5173'
];

/**
 * Verify HMAC signature generated by the client SDK
 */
function verifySignature(timestamp, nonce, signature) {
  if (!timestamp || !nonce || !signature) return false;
  
  // Reject requests older than 5 minutes to prevent replay attacks
  const now = Date.now();
  const reqTime = parseInt(timestamp, 10);
  if (isNaN(reqTime) || Math.abs(now - reqTime) > 300000) return false;

  // Compute expected HMAC-SHA256 signature
  const hmac = crypto.createHmac('sha256', SECRET_KEY);
  hmac.update(`${timestamp}:${nonce}`);
  const expectedSig = hmac.digest('hex');

  try {
    return crypto.timingSafeEqual(
      Buffer.from(signature, 'hex'),
      Buffer.from(expectedSig, 'hex')
    );
  } catch {
    return false;
  }
}

/**
 * Main Vercel Serverless / Node.js API Gateway Handler
 */
export default async function handler(req, res) {
  const origin = req.headers.origin || req.headers.referer || '';
  const secFetchDest = req.headers['sec-fetch-dest'];
  const acceptHeader = req.headers.accept || '';

  // 1. Direct browser access detection
  // If user opens backend URL directly in address bar, browser sends text/html or sec-fetch-dest: document
  const isDirectBrowserVisit = secFetchDest === 'document' || acceptHeader.includes('text/html');

  // 2. Extract SDK signature headers
  const timestamp = req.headers['x-zenith-timestamp'];
  const nonce = req.headers['x-zenith-nonce'];
  const signature = req.headers['x-zenith-signature'];

  // 3. Check if origin is allowed
  const isAllowedOrigin = ALLOWED_ORIGINS.some(allowed => origin.startsWith(allowed));
  const isValidSdkRequest = !isDirectBrowserVisit && isAllowedOrigin && verifySignature(timestamp, nonce, signature);

  // Set Security & CORS Headers
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'SAMEORIGIN');
  res.setHeader('X-XSS-Protection', '1; mode=block');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

  if (isAllowedOrigin) {
    res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Zenith-Timestamp, X-Zenith-Nonce, X-Zenith-Signature');
  }

  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  // If request is direct, unauthorized, or not from authentic website SDK:
  if (!isValidSdkRequest) {
    return res.status(403).send('use zenithstudy.site');
  }

  // 4. Authenticated SDK Request Handler
  try {
    const endpoint = req.query.endpoint || (req.body && req.body.endpoint) || 'default';

    // Serve mapped backend mock responses from data folder
    const dataMap = {
      location: 'myagrc.json',
      toggles: 'd8r65s.json',
      remoteConfig: 'der5u0.json',
      firebase: 'smq7oq.json',
      installations: 'mpy4nn.json'
    };

    const fileName = dataMap[endpoint] || 'myagrc.json';
    const filePath = path.join(process.cwd(), 'data', fileName);

    let responseData = { success: true, message: 'use zenithstudy.site' };

    if (fs.existsSync(filePath)) {
      const raw = fs.readFileSync(filePath, 'utf-8');
      responseData = JSON.parse(raw);
    }

    res.setHeader('Content-Type', 'application/json');
    return res.status(200).json(responseData);
  } catch (error) {
    return res.status(403).send('use zenithstudy.site');
  }
}
